### ISSUE TITLE
Package is no where to be found

### ISSUE THREAD

**Issue by patriqdesigns** [nilportugues/react-jsonschema-form-semanticui#5]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

The package is no where to be found.

### Steps to Reproduce

1. Do npm install react-jsonschema-form-semantic-ui --save
2. Results in: error Couldn't find package "react-jsonschema-form-semantic-ui" on the "npm" registry.

#### Expected behavior

To be able to install the package and use it.

#### Actual behavior

The package is not found, and I am unable to found the package.

### Version

Don't know the version since I was unable to install.

**Comment by plmercereau** [comment]
Indeed this is unfortunate as this package is really nice and helpful!
Here is the workaround I found: I clone, build and install the repository locally:
in a separate folder:
`git clone https://github.com/nilportugues/react-jsonschema-form-semantic-ui.git`
`cd react-jsonschema-form-semantic-ui`
`npm run build:lib`
then in your project folder:
`npm install --save /lib/folder`
Hope it helps while waiting @nilportugues hopefully to provide a more elegant solution!
Thanks anyway @nilportugues, I really love your repository. I wish I could contribute but I am way too newbie to be of some help.

**Comment by nilportugues** [comment]
It's a work in progress, and yet someone found it! 

That's the main reason. I'm working on it on my free time. PR are very welcomed.

**Comment by pratikt-cuelogic** [comment]
looks good.. (y)
any rough date for releasing this ?  to make it available for production use

**Comment by nilportugues** [comment]
@pratikt-cuelogic @plmercereau @patriqdesigns 

https://www.npmjs.com/package/react-jsonschema-form-semanticui :)
