### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by mikkelking** [nilportugues/react-jsonschema-form-semanticui#6]
I like this project - I have been looking for a react form generator for some time, and this may fit the bill, especially as its using react-semantic-ui. Getting it set up is easy, and using in a small project is easy too. Good work!

@nilportugues Did you take this project over from someone else? Are you still active on it? Need some help?

The tests fail for me, that might be a version of react problem - I see a few console errors, so there's probably work to do there.

**Comment by nilportugues** [comment]
Sorry I did not reply, I just manage to get back into react development and NodeJS.

Fixing the test is something I'm willing to do. 

The project itself is a fork of https://github.com/mozilla-services/react-jsonschema-form, but using React SemanticUI  components instead of hard-coded HTML from bootstrap 3.

**Comment by mikkelking** [comment]
Excellent, welcome back. I did work out that it is a fork of the Bootstrap version. My project has it's own components, so we may need to fork it again - is this one or the bootstrap fork the better starting place?

I tried to apply the change for Issue #7 suggested by @ahmadmicro but the data parameter passed is always undefined, so it didn't make sense, and also didn't fix the problem.

I am on React 16, I'm not sure if that's why it doesn't work.

**Comment by nilportugues** [comment]
@mikkelking I've come back to this code lately using as I'm working on a PWA with Next and React 16, so I'll come with a solution for it soon.

If you can provide the jsonschema used to generate the failing form, it would be awesome :)

**Comment by mikkelking** [comment]
That's great, I'll prepare one for you.

**Comment by mikkelking** [comment]
My team mate has fixed a couple of issues already - evidently just bad casing of names (`OnClick` vs `onClick`). I'll get him to submit a PR to save you some of the work.

**Comment by mrslwiseman** [comment]
See PR #86, #87  
Finally got round to this. Hope my work on this helps.
More to come.

**Comment by mikkelking** [comment]
Closing this issue, as we did make some progress on a few things at the time
